### ISSUE TITLE
Mise en place API données traitées

### ISSUE THREAD

**Issue by qloridant** [qloridant/meteofrance_bra_hist#3]
- Utilisation de gitribute ?
- Utilisation de [FastAPI](https://fastapi.tiangolo.com/) ?
-  [Conteneurisation de l'API ? -> Docker ](https://ledatascientist.com/deployer-rapidement-des-modeles-de-ml-avec-fastapi/)
- Hébergement : 
    - Heroku (payant) ?
    - Netlify ?
    - [Deta](https://deta.space/) ?
    - [gitrows](https://gitrows.com/) ?

**Comment by amelie-rondot** [comment]
Solution retenue : utilisation de l'API REST de [GitRows](https://gitrows.com/docs/)
