### ISSUE TITLE
Authenticated requests get a higher rate limit

### ISSUE THREAD

**Issue by qloridant** [qloridant/meteofrance_bra_hist#34]
# Contexte

Certains run de github actions plantent à cause d'une consommation trop importante de l'API :

Authenticated requests get a higher rate limit

# Problème
Nous perdons les informations pour la journée concernée

# Solutions

* Optimiser le nombre de requête à l'API github (par exemple en pushant une seule fois tous les commits) ?
* Mieux comprendre les règles de github pour s'adapter
* Payer

**Comment by amelie-rondot** [comment]
# Rappel du contexte
Chaque jour une action github est déclenchée à 17h pour exécuter : 
- le script `daily_build_url.py` qui : 
  - modifie pour chacun des massifs le fichier url_list.csv, 
  - effectue un commit par fichier modifié, 
  - effectue un push par commit dans la branche master de ce dépôt GitHub 
- le script `daily_extract_url.py` qui : 
   - pour chacun des massifs récupère depuis la branche master de ce dépôt le nouveaux fichier url_list.csv 
   - pour chacun des massifs modifie le fichier hist.csv en conséquence
   - effectue un commit par fichiers modifiés
   - effectue un push par commit dans la branche master de ce dépôt.

Ce qui génère chaque deux fois plus de commits et de pushs dans ce dépôt qu'il n'y a de massifs à traiter (environ 72 commits et pushs par jour)

# Solution choisie
Pour répondre à la problématique de cette issue, il est proposé d'optimiser le nombre de requête à l'API GitHub en limitant le nombre de commits et de push réalisés dans ce dépôt.

Pour se faire, il est proposé de modifer les scripts `daily_build_url.py` et `daily_extract_url.py` pour fusionner tous les commits en un seul commit englobant  toutes les modifications de fichier apportées, avant de ne réaliser qu'un seul push dans ce dépôt GitHub.
